### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by dbridges** [G-Node/python-neuroshare#10]
Any idea how much work it would be to add support for Python 3?

**Comment by souravsingh** [comment]
I would like to work on the issue.I checked the project and it seems that clang might require work for porting to Python3

**Comment by souravsingh** [comment]
I am working on testing the project for Python 3 on my fork.Will update on this soon

**Comment by gicmo** [comment]
@dbridges almost took a year but it should compile and work with python 3 now. I keep this bug open for now because I want to do some more work (unicode, errors, etc pp) before closing this.

**Comment by gicmo** [comment]
As of commit e02d11d I am happy with the py3 support, therefore closing this. Please reopen if there is anything not working.
