### ISSUE TITLE
pip install neuroshare do not work

### ISSUE THREAD

**Issue by samuelgarcia** [G-Node/python-neuroshare#11]
sudo pip install neuroshare do not work for me:

capi/nspy_glue.c:46:24: fatal error: nsAPItypes.h: Aucun fichier ou dossier de ce type
 #include "nsAPItypes.h"

The only way is 
git clone
sudo python setup.py install

**Comment by gicmo** [comment]
hey @samuelgarcia long time no see! Thanks for the report. I will look into it.

**Comment by samuelgarcia** [comment]
Hi.
I think you shoudl add 

sources=['capi/nspy_glue.c', 'capi/nsAPItypes.h', 'capi/nsAPIdllimp.h'])

to your setup.py

but I am not sure.

Samuel

**Comment by gicmo** [comment]
That should hopefully be fixed now. Sorry that it took so long.

**Comment by samuelgarcia** [comment]
thanks.
