### ISSUE TITLE
[py3] capi/nspy_glue.c ‘PyExc_StandardError’ undeclared

### ISSUE THREAD

**Issue by abhay447** [G-Node/python-neuroshare#12]
I was able to adapt the CI for build in python2 and had a successful build but when I tried the same for python3 I encountered the error mentioned above.
Link to my travis.yml [https://github.com/abhay447/python-neuroshare/blob/master/.travis.yml](url)
 For python3 build [https://travis-ci.org/abhay447/python-neuroshare/jobs/106804623](url)

**Comment by abhay447** [comment]
Solved it.. Modified the file capi/nspy_glue.c to accomodate python3.. Moreover I had to edit import statements in all python modules for python3.
[https://github.com/abhay447/python-neuroshare/](my fork of the repo)

**Comment by gicmo** [comment]
Please only close issue when the corresponding pull-request is merged. Thanks!

**Comment by gicmo** [comment]
That is indeed now closed with pr #14 merged.
